# TODO: Adjust joint limits based on actual robot capabilities
# These limits augment or override those specified in the URDF

joint_limits:
  joint1:
    has_velocity_limits: true
    max_velocity: 7.5
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_jerk_limits: false
  joint2:
    has_velocity_limits: true
    max_velocity: 12.0
    has_acceleration_limits: true
    max_acceleration: 3.0
    has_jerk_limits: false
  joint3:
    has_velocity_limits: true
    max_velocity: 12.0
    has_acceleration_limits: true
    max_acceleration: 3.0
    has_jerk_limits: false
  joint4:
    has_velocity_limits: true
    max_velocity: 2.5
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_jerk_limits: false
  joint5:
    has_velocity_limits: true
    max_velocity: 17.5
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_jerk_limits: false

