servo_node:
  ros__parameters:
    move_group_name: arm
    command_out_topic: /arm_controller/joint_trajectory
    command_out_type: trajectory_msgs/JointTrajectory
    publish_period: 0.04
    cartesian_command_in_topic: /servo_twist
    planning_frame: base_link
    ee_frame_name: End_effector
    robot_link_command_frame: base_link
    use_gazebo: false
    status_topic: status
    incoming_command_timeout: 0.5
    scale_linear: 0.4
    scale_rotational: 0.2
    joint_velocity_limits:
      Joint1: 1.0
      Joint2: 1.0
      Joint3: 1.0
      Joint4: 1.0
      Joint5: 1.0
