# Topics
cartesian_command_in_topic: ~/delta_twist_cmds
joint_command_in_topic: ~/delta_joint_cmds
joint_topic: /joint_states
status_topic: ~/status
command_out_topic: /arm_controller/joint_trajectory

# Config
move_group_name: arm
planning_frame: base_link
ee_frame_name: link5
robot_link_command_frame: base_link

# Tuning
linear_scale: 0.4
rotational_scale: 0.8
publish_period: 0.033
low_pass_filter_coeff: 2.0
incoming_command_timeout: 0.1