teleop_node:
  ros__parameters:
    publish_stamped_twist: true
    # --- STICK MAPPING ---
    # Axis 1 = Left Stick Up/Down (Forward/Back)
    # Axis 0 = Left Stick Left/Right (Left/Right)
    # Axis 4 = Right Stick Up/Down (Up/Down)
    # Axis 3 = Right Stick Left/Right (Yaw)
    axis_linear:
      x: 1
      y: 0
      z: 4
    axis_angular:
      yaw: 3
      pitch: 0
      roll: 0
    
    # --- SCALING (Speed) ---
    scale_linear:
      x: 0.4
      y: 0.4
      z: 0.4
    scale_angular:
      yaw: 0.4
      pitch: 0.0
      roll: 0.0

    # --- SAFETY BUTTON ---
    # Button 5 is usually 'RB' (Right Bumper). 
    # You MUST hold this to move.
    enable_button: 5
    require_enable_button: true